/**
 * Subscription Catalog
 * 50+ popular services with manage URL, plan/upgrade URL,
 * Clearbit logo URL (displayed on app's warm card background for theme consistency),
 * and category.
 */

export interface CatalogEntry {
  id: string;
  name: string;
  domain: string;
  /** https://logo.clearbit.com/<domain> */
  logoUrl: string;
  manageUrl: string;
  planUrl: string;
  category: string;
  color: string; // muted, theme-aware pastel
}

const logo = (domain: string) => `https://www.google.com/s2/favicons?domain=${domain}&sz=128`;

export const SUBSCRIPTION_CATALOG: CatalogEntry[] = [
  // ── Entertainment ──────────────────────────────────────────────────────────
  {
    id: 'netflix',
    name: 'Netflix',
    domain: 'netflix.com',
    logoUrl: logo('netflix.com'),
    manageUrl: 'https://www.netflix.com/account',
    planUrl: 'https://www.netflix.com/account/change-plan',
    category: 'Entertainment',
    color: '#f5ddd8',
  },
  {
    id: 'disney-plus',
    name: 'Disney+',
    domain: 'disneyplus.com',
    logoUrl: logo('disneyplus.com'),
    manageUrl: 'https://www.disneyplus.com/account',
    planUrl: 'https://www.disneyplus.com/account/subscription',
    category: 'Entertainment',
    color: '#d8e4f5',
  },
  {
    id: 'amazon-prime',
    name: 'Amazon Prime',
    domain: 'amazon.com',
    logoUrl: logo('amazon.com'),
    manageUrl: 'https://www.amazon.com/mc/pipelines/primesignup',
    planUrl: 'https://www.amazon.com/gp/primecentral',
    category: 'Entertainment',
    color: '#f5ead8',
  },
  {
    id: 'hulu',
    name: 'Hulu',
    domain: 'hulu.com',
    logoUrl: logo('hulu.com'),
    manageUrl: 'https://auth.hulu.com/manage',
    planUrl: 'https://www.hulu.com/account/change-plan',
    category: 'Entertainment',
    color: '#d8f5e8',
  },
  {
    id: 'apple-tv',
    name: 'Apple TV+',
    domain: 'tv.apple.com',
    logoUrl: logo('apple.com'),
    manageUrl: 'https://tv.apple.com/settings',
    planUrl: 'https://appleid.apple.com/account/manage',
    category: 'Entertainment',
    color: '#e8e8e8',
  },
  {
    id: 'youtube-premium',
    name: 'YouTube Premium',
    domain: 'youtube.com',
    logoUrl: logo('youtube.com'),
    manageUrl: 'https://www.youtube.com/paid_memberships',
    planUrl: 'https://www.youtube.com/premium',
    category: 'Entertainment',
    color: '#f5d8d8',
  },
  {
    id: 'hbo-max',
    name: 'Max (HBO)',
    domain: 'max.com',
    logoUrl: logo('max.com'),
    manageUrl: 'https://www.max.com/account',
    planUrl: 'https://www.max.com/account/plan',
    category: 'Entertainment',
    color: '#dcd8f5',
  },
  {
    id: 'crunchyroll',
    name: 'Crunchyroll',
    domain: 'crunchyroll.com',
    logoUrl: logo('crunchyroll.com'),
    manageUrl: 'https://www.crunchyroll.com/account',
    planUrl: 'https://www.crunchyroll.com/account/membership',
    category: 'Entertainment',
    color: '#f5ead8',
  },
  {
    id: 'peacock',
    name: 'Peacock',
    domain: 'peacocktv.com',
    logoUrl: logo('peacocktv.com'),
    manageUrl: 'https://www.peacocktv.com/account',
    planUrl: 'https://www.peacocktv.com/plan',
    category: 'Entertainment',
    color: '#d8f0f5',
  },
  {
    id: 'mubi',
    name: 'MUBI',
    domain: 'mubi.com',
    logoUrl: logo('mubi.com'),
    manageUrl: 'https://mubi.com/account',
    planUrl: 'https://mubi.com/account',
    category: 'Entertainment',
    color: '#f5d8d8',
  },

  // ── Music ──────────────────────────────────────────────────────────────────
  {
    id: 'spotify',
    name: 'Spotify',
    domain: 'spotify.com',
    logoUrl: logo('spotify.com'),
    manageUrl: 'https://www.spotify.com/account/overview/',
    planUrl: 'https://www.spotify.com/account/subscription/',
    category: 'Music',
    color: '#d8f5e0',
  },
  {
    id: 'apple-music',
    name: 'Apple Music',
    domain: 'music.apple.com',
    logoUrl: logo('apple.com'),
    manageUrl: 'https://appleid.apple.com/account/manage',
    planUrl: 'https://appleid.apple.com/account/manage',
    category: 'Music',
    color: '#f5d8e0',
  },
  {
    id: 'tidal',
    name: 'Tidal',
    domain: 'tidal.com',
    logoUrl: logo('tidal.com'),
    manageUrl: 'https://account.tidal.com',
    planUrl: 'https://account.tidal.com/settings',
    category: 'Music',
    color: '#e0e0e0',
  },
  {
    id: 'amazon-music',
    name: 'Amazon Music',
    domain: 'music.amazon.com',
    logoUrl: logo('amazon.com'),
    manageUrl: 'https://music.amazon.com/account',
    planUrl: 'https://music.amazon.com/prime',
    category: 'Music',
    color: '#f5ead8',
  },
  {
    id: 'youtube-music',
    name: 'YouTube Music',
    domain: 'music.youtube.com',
    logoUrl: logo('youtube.com'),
    manageUrl: 'https://music.youtube.com/paid_memberships',
    planUrl: 'https://music.youtube.com/music_premium',
    category: 'Music',
    color: '#f5d8d8',
  },

  // ── AI Tools ───────────────────────────────────────────────────────────────
  {
    id: 'chatgpt',
    name: 'ChatGPT Plus',
    domain: 'openai.com',
    logoUrl: logo('openai.com'),
    manageUrl: 'https://platform.openai.com/account/billing/overview',
    planUrl: 'https://chat.openai.com/#pricing',
    category: 'AI Tools',
    color: '#e0ede8',
  },
  {
    id: 'claude',
    name: 'Claude Pro',
    domain: 'claude.ai',
    logoUrl: logo('anthropic.com'),
    manageUrl: 'https://claude.ai/settings',
    planUrl: 'https://claude.ai/upgrade',
    category: 'AI Tools',
    color: '#f5ead8',
  },
  {
    id: 'midjourney',
    name: 'Midjourney',
    domain: 'midjourney.com',
    logoUrl: logo('midjourney.com'),
    manageUrl: 'https://www.midjourney.com/account',
    planUrl: 'https://www.midjourney.com/account',
    category: 'AI Tools',
    color: '#dcd8f5',
  },
  {
    id: 'grammarly',
    name: 'Grammarly',
    domain: 'grammarly.com',
    logoUrl: logo('grammarly.com'),
    manageUrl: 'https://account.grammarly.com',
    planUrl: 'https://www.grammarly.com/upgrade',
    category: 'AI Tools',
    color: '#d8eed8',
  },
  {
    id: 'perplexity',
    name: 'Perplexity Pro',
    domain: 'perplexity.ai',
    logoUrl: logo('perplexity.ai'),
    manageUrl: 'https://www.perplexity.ai/settings/account',
    planUrl: 'https://www.perplexity.ai/pro',
    category: 'AI Tools',
    color: '#d8e8f5',
  },

  // ── Developer Tools ────────────────────────────────────────────────────────
  {
    id: 'github',
    name: 'GitHub Pro',
    domain: 'github.com',
    logoUrl: logo('github.com'),
    manageUrl: 'https://github.com/settings/billing',
    planUrl: 'https://github.com/settings/billing/plans',
    category: 'Developer Tools',
    color: '#e8e4f0',
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    domain: 'gitlab.com',
    logoUrl: logo('gitlab.com'),
    manageUrl: 'https://gitlab.com/-/profile/billing',
    planUrl: 'https://about.gitlab.com/pricing/',
    category: 'Developer Tools',
    color: '#f5e4d8',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    domain: 'vercel.com',
    logoUrl: logo('vercel.com'),
    manageUrl: 'https://vercel.com/account/billing',
    planUrl: 'https://vercel.com/pricing',
    category: 'Developer Tools',
    color: '#e8e8e8',
  },
  {
    id: 'netlify',
    name: 'Netlify',
    domain: 'netlify.com',
    logoUrl: logo('netlify.com'),
    manageUrl: 'https://app.netlify.com/teams/billing',
    planUrl: 'https://www.netlify.com/pricing/',
    category: 'Developer Tools',
    color: '#d8f0f5',
  },
  {
    id: 'digital-ocean',
    name: 'DigitalOcean',
    domain: 'digitalocean.com',
    logoUrl: logo('digitalocean.com'),
    manageUrl: 'https://cloud.digitalocean.com/account/billing',
    planUrl: 'https://www.digitalocean.com/pricing',
    category: 'Developer Tools',
    color: '#d8e8f5',
  },
  {
    id: 'jetbrains',
    name: 'JetBrains All Products',
    domain: 'jetbrains.com',
    logoUrl: logo('jetbrains.com'),
    manageUrl: 'https://account.jetbrains.com/licenses',
    planUrl: 'https://www.jetbrains.com/store/',
    category: 'Developer Tools',
    color: '#f5d8e0',
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    domain: 'cloudflare.com',
    logoUrl: logo('cloudflare.com'),
    manageUrl: 'https://dash.cloudflare.com/profile/billing',
    planUrl: 'https://www.cloudflare.com/plans/',
    category: 'Developer Tools',
    color: '#f5ead8',
  },

  // ── Design ─────────────────────────────────────────────────────────────────
  {
    id: 'figma',
    name: 'Figma',
    domain: 'figma.com',
    logoUrl: logo('figma.com'),
    manageUrl: 'https://www.figma.com/settings',
    planUrl: 'https://www.figma.com/pricing/',
    category: 'Design',
    color: '#f5d8d8',
  },
  {
    id: 'adobe',
    name: 'Adobe Creative Cloud',
    domain: 'adobe.com',
    logoUrl: logo('adobe.com'),
    manageUrl: 'https://account.adobe.com/plans',
    planUrl: 'https://www.adobe.com/creativecloud/plans.html',
    category: 'Design',
    color: '#f5d8d8',
  },
  {
    id: 'canva',
    name: 'Canva Pro',
    domain: 'canva.com',
    logoUrl: logo('canva.com'),
    manageUrl: 'https://www.canva.com/settings/billing/',
    planUrl: 'https://www.canva.com/upgrade/',
    category: 'Design',
    color: '#d8f0d8',
  },
  {
    id: 'framer',
    name: 'Framer',
    domain: 'framer.com',
    logoUrl: logo('framer.com'),
    manageUrl: 'https://www.framer.com/projects/',
    planUrl: 'https://www.framer.com/pricing/',
    category: 'Design',
    color: '#dcd8f5',
  },

  // ── Productivity ───────────────────────────────────────────────────────────
  {
    id: 'notion',
    name: 'Notion',
    domain: 'notion.so',
    logoUrl: logo('notion.so'),
    manageUrl: 'https://www.notion.so/settings-members',
    planUrl: 'https://www.notion.so/pricing',
    category: 'Productivity',
    color: '#e8e8e8',
  },
  {
    id: 'evernote',
    name: 'Evernote',
    domain: 'evernote.com',
    logoUrl: logo('evernote.com'),
    manageUrl: 'https://www.evernote.com/Settings.action',
    planUrl: 'https://evernote.com/upgrade',
    category: 'Productivity',
    color: '#d8f0d8',
  },
  {
    id: 'todoist',
    name: 'Todoist Pro',
    domain: 'todoist.com',
    logoUrl: logo('todoist.com'),
    manageUrl: 'https://todoist.com/prefs/account',
    planUrl: 'https://todoist.com/pricing',
    category: 'Productivity',
    color: '#f5d8d8',
  },
  {
    id: 'asana',
    name: 'Asana',
    domain: 'asana.com',
    logoUrl: logo('asana.com'),
    manageUrl: 'https://app.asana.com/-/admin_console',
    planUrl: 'https://asana.com/pricing',
    category: 'Productivity',
    color: '#f5e0d8',
  },
  {
    id: 'linear',
    name: 'Linear',
    domain: 'linear.app',
    logoUrl: logo('linear.app'),
    manageUrl: 'https://linear.app/settings/billing',
    planUrl: 'https://linear.app/pricing',
    category: 'Productivity',
    color: '#dcd8f5',
  },
  {
    id: 'clickup',
    name: 'ClickUp',
    domain: 'clickup.com',
    logoUrl: logo('clickup.com'),
    manageUrl: 'https://app.clickup.com/settings/billing',
    planUrl: 'https://clickup.com/pricing',
    category: 'Productivity',
    color: '#f0d8f5',
  },
  {
    id: 'monday',
    name: 'Monday.com',
    domain: 'monday.com',
    logoUrl: logo('monday.com'),
    manageUrl: 'https://auth.monday.com/subscription',
    planUrl: 'https://monday.com/pricing',
    category: 'Productivity',
    color: '#f5d8d8',
  },
  {
    id: 'airtable',
    name: 'Airtable',
    domain: 'airtable.com',
    logoUrl: logo('airtable.com'),
    manageUrl: 'https://airtable.com/account',
    planUrl: 'https://airtable.com/pricing',
    category: 'Productivity',
    color: '#d8eef5',
  },

  // ── Cloud / Storage ────────────────────────────────────────────────────────
  {
    id: 'google-one',
    name: 'Google One',
    domain: 'one.google.com',
    logoUrl: logo('google.com'),
    manageUrl: 'https://one.google.com/storage',
    planUrl: 'https://one.google.com/about/plans',
    category: 'Cloud',
    color: '#d8e8f5',
  },
  {
    id: 'icloud',
    name: 'iCloud+',
    domain: 'icloud.com',
    logoUrl: logo('apple.com'),
    manageUrl: 'https://appleid.apple.com/account/manage',
    planUrl: 'https://support.apple.com/en-us/HT201238',
    category: 'Cloud',
    color: '#e8e8e8',
  },
  {
    id: 'dropbox',
    name: 'Dropbox',
    domain: 'dropbox.com',
    logoUrl: logo('dropbox.com'),
    manageUrl: 'https://www.dropbox.com/account/plan',
    planUrl: 'https://www.dropbox.com/upgrade',
    category: 'Cloud',
    color: '#d8e8f5',
  },
  {
    id: 'onedrive',
    name: 'OneDrive',
    domain: 'onedrive.com',
    logoUrl: logo('microsoft.com'),
    manageUrl: 'https://account.microsoft.com/services',
    planUrl: 'https://www.microsoft.com/en-us/microsoft-365/onedrive/compare-onedrive-plans',
    category: 'Cloud',
    color: '#d8eaf5',
  },
  {
    id: 'backblaze',
    name: 'Backblaze',
    domain: 'backblaze.com',
    logoUrl: logo('backblaze.com'),
    manageUrl: 'https://secure.backblaze.com/account.htm',
    planUrl: 'https://www.backblaze.com/cloud-backup/pricing',
    category: 'Cloud',
    color: '#f5e4d8',
  },

  // ── Security / VPN ─────────────────────────────────────────────────────────
  {
    id: 'nordvpn',
    name: 'NordVPN',
    domain: 'nordvpn.com',
    logoUrl: logo('nordvpn.com'),
    manageUrl: 'https://my.nordaccount.com/dashboard/nordvpn/',
    planUrl: 'https://nordvpn.com/pricing/',
    category: 'Productivity',
    color: '#d8e0f5',
  },
  {
    id: 'expressvpn',
    name: 'ExpressVPN',
    domain: 'expressvpn.com',
    logoUrl: logo('expressvpn.com'),
    manageUrl: 'https://www.expressvpn.com/subscriptions',
    planUrl: 'https://www.expressvpn.com/order',
    category: 'Productivity',
    color: '#f5d8d8',
  },
  {
    id: '1password',
    name: '1Password',
    domain: '1password.com',
    logoUrl: logo('1password.com'),
    manageUrl: 'https://my.1password.com/billing',
    planUrl: 'https://1password.com/sign-up/',
    category: 'Productivity',
    color: '#d8eef5',
  },

  // ── Other ──────────────────────────────────────────────────────────────────
  {
    id: 'microsoft-365',
    name: 'Microsoft 365',
    domain: 'microsoft.com',
    logoUrl: logo('microsoft.com'),
    manageUrl: 'https://account.microsoft.com/services',
    planUrl: 'https://www.microsoft.com/en-us/microsoft-365',
    category: 'Productivity',
    color: '#d8eaf5',
  },
  {
    id: 'duolingo',
    name: 'Duolingo Plus',
    domain: 'duolingo.com',
    logoUrl: logo('duolingo.com'),
    manageUrl: 'https://www.duolingo.com/settings',
    planUrl: 'https://www.duolingo.com/plus',
    category: 'Other',
    color: '#d8f5d8',
  },
  {
    id: 'linkedin-premium',
    name: 'LinkedIn Premium',
    domain: 'linkedin.com',
    logoUrl: logo('linkedin.com'),
    manageUrl: 'https://www.linkedin.com/premium/manage',
    planUrl: 'https://www.linkedin.com/premium/products',
    category: 'Productivity',
    color: '#d8e4f5',
  },
  {
    id: 'medium',
    name: 'Medium',
    domain: 'medium.com',
    logoUrl: logo('medium.com'),
    manageUrl: 'https://medium.com/me/membership',
    planUrl: 'https://medium.com/membership',
    category: 'Other',
    color: '#e8e8e8',
  },
  {
    id: 'substack',
    name: 'Substack',
    domain: 'substack.com',
    logoUrl: logo('substack.com'),
    manageUrl: 'https://substack.com/account',
    planUrl: 'https://substack.com/account',
    category: 'Other',
    color: '#f5ecd8',
  },
];

/** Look up a catalog entry by subscription name (case-insensitive partial match) */
export const findCatalogEntry = (name: string): CatalogEntry | undefined => {
  if (!name.trim()) return undefined;
  const q = name.toLowerCase().trim();
  return SUBSCRIPTION_CATALOG.find(
    (e) =>
      e.name.toLowerCase().includes(q) ||
      q.includes(e.id.replace(/-/g, ' ')) ||
      q.includes(e.name.toLowerCase())
  );
};
